version: '3.9'

services:
    nginx_mezzio:
        image: nginx:1.23
        ports:
            - "80:80"
        volumes:
            - .:/var/www/mezzio #see rootDir ./docker-conf/nginxSites.confs
            #- /home/bob/DEV/www/pma-5.1.3:/var/www/pma.ru #see rootDir ./docker-conf/nginxSites.confs
            - ./docker-conf/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./docker-conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            #- ./docker-conf/nginx/error.log:/var/log/nginx/error.log
        networks:
            - network_mezzio
    php_mezzio:
        #nginx listen   php_mezzio:9000   
        build:
            args:
                - arg_user=bob
                - arg_uid=1000
                - arg_gid=1000
            context: .
            dockerfile: Dockerfile
        container_name: php_mezzio
        image: php_mezzio
        volumes:
            - .:/var/www/mezzio #see rootDir ./docker-conf/nginxSites.confs
            #- /home/bob/DEV/www/pma-5.1.3:/var/www/pma.ru #see rootDir ./docker-conf/nginxSites.confs
            #- ./docker-conf/docker-entrypoint.sh:/var/www/mezzio/docker-conf/docker-entrypoint.sh
        networks:
            - network_mezzio
        entrypoint: /var/www/mezzio/docker-conf/docker-entrypoint.sh
        #docker-entrypoint.sh ==> cd /var/www/mezzio && composer update  
        #May be better: docker-compose exec php_mezzio    composer install/update?
        #extra_hosts:               
            #- "tt.ru:host-gateway"  #for tt.ru/API/     

networks:
    network_mezzio:
        driver: bridge
