version: '3.9'

services:
    ddd-backend-nginx:
        restart: no
        build:
            context: ../backend
            dockerfile: docker/dev/nginx/Dockerfile
        ports:
            - "80:80"
        networks:
            - ddd-backend-network
        volumes:
            - .:/var/www/ddd

    ddd-backend-php:
        #nginx listen ddd-backend-php:9000   
        restart: no
        build:
            args:
                - arg_user=ddd
                - arg_uid=1000
                - arg_gid=1000
            context: ../backend
            dockerfile: docker/dev/php/Dockerfile
        volumes:
            - .:/var/www/ddd
        networks:
            - ddd-backend-network

    ddd-backend-mariadb: #configDB.php host=ddd-backend-mariadb, NOT localhost!          
        restart: no
        build:            
            context: ../backend
            dockerfile: docker/dev/mariadb/Dockerfile               
        environment:
            MARIADB_ROOT_HOST: localhost
            MARIADB_ROOT_PASSWORD: 0000
            MARIADB_USER: uddd
            MARIADB_PASSWORD: pddd    
            MARIADB_DATABASE: ddd          
        volumes:
            - ddd-backend-mariadb-volume:/var/lib/mysql #named volume - persistent, does not disappear after docker-compose down
        ports:
            - "3306:3306"         
        networks:
            - ddd-backend-network        

networks:
    ddd-backend-network:
        driver: bridge

volumes:
    ddd-backend-mariadb-volume: #named volume - persistent, does not disappear after docker-compose down        
