<?php 
/* $this->layout()->setTemplate('layout::info');  // src\App\ConfigProvider.php 'templates'=>'paths'=> ['layout' => [__DIR__ . '/../templates/layout'],

or in Handler 
return new HtmlResponse($this->template->render('app::info', [
            'layout' => 'layout::info',  // src\App\ConfigProvider.php 'templates'=>'paths'=> ['layout' => [__DIR__ . '/../templates/layout'],
            'info' => $this->template,
        ]));

        */
print_r($this->info);
