FROM nginx:1.23-alpine

#WORKDIR /var/www ???
 
COPY mezzio /var/www/wheretobuy_api

COPY docker/dev/nginx/nginx.conf /etc/nginx/conf.d/default.conf
        
                  
            
            
            
         

